apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-binding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    # The namespace of the SA
    namespace: argo
roleRef:
  kind: Role
  name: operate-workflow-role
  apiGroup: rbac.authorization.k8s.io